package youtube

import (
	"context"
	"fmt"
	"net/url"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/tituscheng/ytgo/internal/extractor"
	"github.com/tituscheng/ytgo/internal/extractor/youtube/innertube"
	"github.com/tituscheng/ytgo/internal/transport"
)

var (
	videoIDRegex    = regexp.MustCompile(`(?:v=|\/v\/|\/embed\/|\/shorts\/|\/live\/|youtu\.be\/|\/watch\?v%3D)([0-9A-Za-z_-]{11})`)
	playlistIDRegex = regexp.MustCompile(`[&?]list=([A-Za-z0-9_-]+)`)
)

// Extractor implements extractor.InfoExtractor for YouTube.
type Extractor struct {
	client  *innertube.Client
	Enrich  bool // if true, makes secondary API calls for additional metadata
}

// NewExtractor creates a new YouTube extractor that uses the tuned
// transport (connection pooling, HTTP/2, keep-alives) for all Innertube calls.
func NewExtractor(timeout time.Duration) *Extractor {
	return &Extractor{
		client: innertube.NewClientWithTransport(transport.NewTunedTransport(), timeout),
	}
}

// Name returns the extractor identifier.
func (e *Extractor) Name() string { return "youtube" }

// Suitable reports whether the URL is a YouTube link.
func (e *Extractor) Suitable(rawURL string) bool {
	if videoIDRegex.MatchString(rawURL) {
		return true
	}
	u, err := url.Parse(rawURL)
	if err != nil {
		return false
	}
	host := strings.ToLower(u.Hostname())
	// Exact domain + proper subdomain check (prevents notyoutube.com, fakeyoutube.com, etc.).
	return host == "youtube.com" || strings.HasSuffix(host, ".youtube.com") || host == "youtu.be"
}

// Extract fetches metadata for the given YouTube URL.
func (e *Extractor) Extract(ctx context.Context, rawURL string) (*extractor.VideoInfo, error) {
	videoID := extractVideoID(rawURL)
	playlistID := extractPlaylistID(rawURL)

	// If no video ID but we have a playlist ID, extract the playlist directly
	if videoID == "" && playlistID != "" {
		return e.extractPlaylist(ctx, playlistID, rawURL)
	}
	if videoID == "" {
		return nil, fmt.Errorf("could not extract video ID from URL: %s", rawURL)
	}

	return e.extractVideo(ctx, videoID, rawURL)
}

func (e *Extractor) extractVideo(ctx context.Context, videoID, rawURL string) (*extractor.VideoInfo, error) {
	var resp *innertube.PlayerResponse
	var err error
	if e.Enrich {
		resp, err = e.client.PlayerWithEnrichment(ctx, videoID)
	} else {
		resp, err = e.client.Player(ctx, videoID)
	}
	if err != nil {
		return nil, fmt.Errorf("get video failed: %w", err)
	}

	info := &extractor.VideoInfo{
		ID:          videoID,
		Title:       resp.VideoDetails.Title,
		Description: resp.VideoDetails.ShortDescription,
		ChannelID:   resp.VideoDetails.ChannelID,
		Uploader:    resp.VideoDetails.Author,
		Channel:     resp.VideoDetails.Author,
		OriginalURL: rawURL,
		WebpageURL:  fmt.Sprintf("https://www.youtube.com/watch?v=%s", videoID),
	}

	if views, _ := strconv.ParseInt(resp.VideoDetails.ViewCount, 10, 64); views > 0 {
		info.ViewCount = views
	}
	if likes, _ := strconv.ParseInt(resp.VideoDetails.LikeCount, 10, 64); likes > 0 {
		info.LikeCount = likes
	}
	if sec, _ := strconv.Atoi(resp.VideoDetails.LengthSeconds); sec > 0 {
		info.Duration = time.Duration(sec) * time.Second
	}

	// Publish date from microformat
	if resp.Microformat.PlayerMicroformatRenderer.PublishDate != "" {
		info.UploadDate = strings.ReplaceAll(resp.Microformat.PlayerMicroformatRenderer.PublishDate, "-", "")
	} else if resp.Microformat.PlayerMicroformatRenderer.UploadDate != "" {
		info.UploadDate = strings.ReplaceAll(resp.Microformat.PlayerMicroformatRenderer.UploadDate, "-", "")
	}

	// Thumbnails
	for _, t := range resp.VideoDetails.Thumbnail.Thumbnails {
		info.Thumbnails = append(info.Thumbnails, extractor.Thumbnail{
			URL:    t.URL,
			Width:  t.Width,
			Height: t.Height,
		})
	}

	// Formats
	for _, f := range resp.StreamingData.Formats {
		info.Formats = append(info.Formats, mapFormat(f))
	}
	for _, f := range resp.StreamingData.AdaptiveFormats {
		info.Formats = append(info.Formats, mapFormat(f))
	}

	// Subtitles / Captions
	if resp.Captions != nil && len(resp.Captions.PlayerCaptionsTracklistRenderer.CaptionTracks) > 0 {
		info.Subtitles = make(map[string][]extractor.Subtitle)
		info.AutoSubtitles = make(map[string][]extractor.Subtitle)
		for _, ct := range resp.Captions.PlayerCaptionsTracklistRenderer.CaptionTracks {
			lang := normalizeLang(ct.LanguageCode)
			isAuto := ct.Kind == "asr" || strings.Contains(ct.Name.String(), "auto")
			sub := extractor.Subtitle{
				URL:           ct.BaseURL,
				Language:      lang,
				Name:          ct.Name.String(),
				Ext:           "json3",
				AutoGenerated: isAuto,
			}
			if isAuto {
				info.AutoSubtitles[lang] = append(info.AutoSubtitles[lang], sub)
			} else {
				info.Subtitles[lang] = append(info.Subtitles[lang], sub)
			}
		}
	}

	return info, nil
}

func (e *Extractor) extractPlaylist(ctx context.Context, playlistID, rawURL string) (*extractor.VideoInfo, error) {
	pl, err := e.client.Playlist(ctx, playlistID)
	if err != nil {
		return nil, fmt.Errorf("get playlist failed: %w", err)
	}

	info := &extractor.VideoInfo{
		ID:            playlistID,
		Title:         pl.Title,
		Description:   pl.Description,
		Uploader:      pl.Author,
		Channel:       pl.Author,
		PlaylistID:    playlistID,
		PlaylistTitle: pl.Title,
		OriginalURL:   rawURL,
		WebpageURL:    fmt.Sprintf("https://www.youtube.com/playlist?list=%s", playlistID),
	}

	for _, entry := range pl.Entries {
		child := &extractor.VideoInfo{
			ID:          entry.ID,
			Title:       entry.Title,
			Uploader:    entry.Author,
			Channel:     entry.Author,
			Duration:    entry.Duration,
			OriginalURL: fmt.Sprintf("https://www.youtube.com/watch?v=%s", entry.ID),
			WebpageURL:  fmt.Sprintf("https://www.youtube.com/watch?v=%s", entry.ID),
		}
		for _, t := range entry.Thumbnails {
			child.Thumbnails = append(child.Thumbnails, extractor.Thumbnail{
				URL:    t.URL,
				Width:  t.Width,
				Height: t.Height,
			})
		}
		info.Entries = append(info.Entries, child)
	}

	return info, nil
}

func mapFormat(f innertube.Format) extractor.Format {
	ext, vcodec, acodec := parseMimeType(f.MimeType)
	format := extractor.Format{
		FormatID:      strconv.Itoa(f.ItagNo),
		URL:           f.URL,
		Ext:           ext,
		Width:         f.Width,
		Height:        f.Height,
		FPS:           float64(f.FPS),
		VideoCodec:    vcodec,
		AudioCodec:    acodec,
		TBR:           float64(f.Bitrate) / 1000,
		Filesize:      f.ContentLength,
		Quality:       f.Quality,
		QualityLabel:  f.QualityLabel,
		AudioChannels: f.AudioChannels,
	}
	format.HasVideo = strings.HasPrefix(f.MimeType, "video/")
	format.HasAudio = strings.HasPrefix(f.MimeType, "audio/")
	if format.HasVideo && f.AudioChannels > 0 {
		format.HasAudio = true
	}
	return format
}

func parseMimeType(mime string) (ext, vcodec, acodec string) {
	full := mime
	if idx := strings.Index(mime, ";"); idx >= 0 {
		mime = strings.TrimSpace(mime[:idx])
	}
	parts := strings.Split(mime, "/")
	if len(parts) == 2 {
		ext = parts[1]
	}
	// Codecs from mime type: video/webm; codecs="vp9" => vp9
	prefix := "codecs=\""
	start := strings.Index(full, prefix)
	if start >= 0 {
		start += len(prefix)
		end := strings.Index(full[start:], "\"")
		if end >= 0 {
			codecs := full[start : start+end]
			codecParts := strings.Split(codecs, ",")
			for i, p := range codecParts {
				p = strings.TrimSpace(p)
				if i == 0 {
					vcodec = p
				} else {
					acodec = p
				}
			}
		}
	}
	return
}

func extractVideoID(u string) string {
	m := videoIDRegex.FindStringSubmatch(u)
	if len(m) > 1 {
		return m[1]
	}
	return ""
}

func extractPlaylistID(u string) string {
	m := playlistIDRegex.FindStringSubmatch(u)
	if len(m) > 1 {
		return m[1]
	}
	return ""
}

func normalizeLang(l string) string {
	if idx := strings.Index(l, "-"); idx > 0 {
		return l[:idx]
	}
	return l
}
