package youtube

import (
	"context"
	"fmt"
	"net/http"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/kkdai/youtube/v2"

	"ytgo/internal/extractor"
)

var (
	videoIDRegex    = regexp.MustCompile(`(?:v=|\/v\/|\/embed\/|\/shorts\/|\/live\/|youtu\.be\/|\/watch\?v%3D)([0-9A-Za-z_-]{11})`)
	playlistIDRegex = regexp.MustCompile(`[&?]list=([A-Za-z0-9_-]+)`)
)

// Extractor implements extractor.InfoExtractor for YouTube.
type Extractor struct {
	client *youtube.Client
}

// NewExtractor creates a new YouTube extractor.
func NewExtractor(timeout time.Duration) *Extractor {
	c := youtube.Client{HTTPClient: &http.Client{Timeout: timeout}}
	return &Extractor{client: &c}
}

// Name returns the extractor identifier.
func (e *Extractor) Name() string { return "youtube" }

// Suitable reports whether the URL is a YouTube link.
func (e *Extractor) Suitable(url string) bool {
	return videoIDRegex.MatchString(url) || strings.Contains(url, "youtube.com") || strings.Contains(url, "youtu.be")
}

// Extract fetches metadata for the given YouTube URL.
func (e *Extractor) Extract(ctx context.Context, rawURL string) (*extractor.VideoInfo, error) {
	videoID := extractVideoID(rawURL)
	playlistID := extractPlaylistID(rawURL)

	// If no video ID but we have a playlist ID, extract the playlist directly
	if videoID == "" && playlistID != "" {
		return e.extractPlaylist(ctx, playlistID, rawURL)
	}
	if videoID == "" {
		return nil, fmt.Errorf("could not extract video ID from URL: %s", rawURL)
	}

	return e.extractVideo(ctx, videoID, rawURL)
}

func (e *Extractor) extractVideo(ctx context.Context, videoID, rawURL string) (*extractor.VideoInfo, error) {
	video, err := e.client.GetVideoContext(ctx, rawURL)
	if err != nil {
		return nil, fmt.Errorf("get video failed: %w", err)
	}

	info := &extractor.VideoInfo{
		ID:          videoID,
		Title:       video.Title,
		Description: video.Description,
		Duration:    video.Duration,
		ViewCount:   int64(video.Views),
		Uploader:    video.Author,
		Channel:     video.Author,
		ChannelID:   video.ChannelID,
		UploadDate:  video.PublishDate.Format("20060102"),
		OriginalURL: rawURL,
		WebpageURL:  fmt.Sprintf("https://www.youtube.com/watch?v=%s", videoID),
	}

	// Thumbnails
	for _, t := range video.Thumbnails {
		info.Thumbnails = append(info.Thumbnails, extractor.Thumbnail{
			URL:    t.URL,
			Width:  int(t.Width),
			Height: int(t.Height),
		})
	}

	// Formats
	for _, f := range video.Formats {
		info.Formats = append(info.Formats, mapFormat(f))
	}

	// Subtitles / Captions
	if len(video.CaptionTracks) > 0 {
		info.Subtitles = make(map[string][]extractor.Subtitle)
		info.AutoSubtitles = make(map[string][]extractor.Subtitle)
		for _, ct := range video.CaptionTracks {
			lang := normalizeLang(ct.Name.SimpleText)
			isAuto := strings.Contains(ct.Name.SimpleText, "auto")
			sub := extractor.Subtitle{
				URL:           ct.BaseURL,
				Language:      lang,
				Name:          ct.Name.SimpleText,
				Ext:           "json3",
				AutoGenerated: isAuto,
			}
			if isAuto {
				info.AutoSubtitles[lang] = append(info.AutoSubtitles[lang], sub)
			} else {
				info.Subtitles[lang] = append(info.Subtitles[lang], sub)
			}
		}
	}

	return info, nil
}

func mapFormat(f youtube.Format) extractor.Format {
	ext, vcodec, acodec := parseMimeType(f.MimeType)
	format := extractor.Format{
		FormatID:      strconv.Itoa(f.ItagNo),
		URL:           f.URL,
		Ext:           ext,
		Width:         f.Width,
		Height:        f.Height,
		FPS:           float64(f.FPS),
		VideoCodec:    vcodec,
		AudioCodec:    acodec,
		TBR:           float64(f.Bitrate) / 1000,
		Filesize:      f.ContentLength,
		Quality:       f.Quality,
		QualityLabel:  f.QualityLabel,
		AudioChannels: f.AudioChannels,
	}
	format.HasVideo = strings.HasPrefix(f.MimeType, "video/")
	format.HasAudio = strings.HasPrefix(f.MimeType, "audio/")
	if format.HasVideo && format.AudioCodec != "" {
		format.HasAudio = true
	}
	return format
}

func parseMimeType(mime string) (ext, vcodec, acodec string) {
	full := mime
	if idx := strings.Index(mime, ";"); idx >= 0 {
		mime = strings.TrimSpace(mime[:idx])
	}
	parts := strings.Split(mime, "/")
	if len(parts) == 2 {
		ext = parts[1]
	}
	// Codecs from mime type: video/webm; codecs="vp9" => vp9
	prefix := "codecs=\""
	start := strings.Index(full, prefix)
	if start >= 0 {
		start += len(prefix)
		end := strings.Index(full[start:], "\"")
		if end >= 0 {
			codecs := full[start : start+end]
			codecParts := strings.Split(codecs, ",")
			for i, p := range codecParts {
				p = strings.TrimSpace(p)
				if i == 0 {
					vcodec = p
				} else {
					acodec = p
				}
			}
		}
	}
	return
}

func extractVideoID(u string) string {
	m := videoIDRegex.FindStringSubmatch(u)
	if len(m) > 1 {
		return m[1]
	}
	return ""
}

func extractPlaylistID(u string) string {
	m := playlistIDRegex.FindStringSubmatch(u)
	if len(m) > 1 {
		return m[1]
	}
	return ""
}

func normalizeLang(l string) string {
	if idx := strings.Index(l, "-"); idx > 0 {
		return l[:idx]
	}
	return l
}
