// Package ytgo provides public types used throughout ytgo.
package ytgo

import "time"

// Format represents a single downloadable stream.
type Format struct {
	FormatID       string  `json:"format_id"`
	URL            string  `json:"url"`
	ManifestURL    string  `json:"manifest_url,omitempty"`
	Ext            string  `json:"ext"`
	Width          int     `json:"width,omitempty"`
	Height         int     `json:"height,omitempty"`
	FPS            float64 `json:"fps,omitempty"`
	VideoCodec     string  `json:"vcodec,omitempty"`
	AudioCodec     string  `json:"acodec,omitempty"`
	VBR            float64 `json:"vbr,omitempty"`
	ABR            float64 `json:"abr,omitempty"`
	TBR            float64 `json:"tbr,omitempty"`
	Filesize       int64   `json:"filesize,omitempty"`
	FilesizeApprox int64   `json:"filesize_approx,omitempty"`
	Quality        string  `json:"quality,omitempty"`
	QualityLabel   string  `json:"quality_label,omitempty"`
	AudioChannels  int     `json:"audio_channels,omitempty"`
	Language       string  `json:"language,omitempty"`
	HasVideo       bool    `json:"has_video"`
	HasAudio       bool    `json:"has_audio"`
}

// Subtitle represents a subtitle track.
type Subtitle struct {
	URL           string `json:"url"`
	Ext           string `json:"ext"`
	Language      string `json:"language"`
	Name          string `json:"name"`
	AutoGenerated bool   `json:"auto_generated"`
}

// Thumbnail represents a thumbnail image.
type Thumbnail struct {
	URL    string `json:"url"`
	Width  int    `json:"width"`
	Height int    `json:"height"`
	ID     string `json:"id,omitempty"`
}

// Chapter represents a video chapter marker.
type Chapter struct {
	Title     string        `json:"title"`
	StartTime time.Duration `json:"start_time"`
	EndTime   time.Duration `json:"end_time,omitempty"`
}

// VideoInfo holds all metadata for a video or playlist entry.
type VideoInfo struct {
	ID          string        `json:"id"`
	Title       string        `json:"title"`
	Description string        `json:"description,omitempty"`
	Uploader    string        `json:"uploader,omitempty"`
	UploaderID  string        `json:"uploader_id,omitempty"`
	Channel     string        `json:"channel,omitempty"`
	ChannelID   string        `json:"channel_id,omitempty"`
	UploadDate  string        `json:"upload_date,omitempty"`
	Duration    time.Duration `json:"duration,omitempty"`
	ViewCount   int64         `json:"view_count,omitempty"`
	LikeCount   int64         `json:"like_count,omitempty"`
	WebpageURL  string        `json:"webpage_url,omitempty"`
	OriginalURL string        `json:"original_url,omitempty"`

	Formats       []Format              `json:"formats"`
	Thumbnails    []Thumbnail           `json:"thumbnails,omitempty"`
	Subtitles     map[string][]Subtitle `json:"subtitles,omitempty"`
	AutoSubtitles map[string][]Subtitle `json:"automatic_captions,omitempty"`
	Chapters      []Chapter             `json:"chapters,omitempty"`

	Playlist      string `json:"playlist,omitempty"`
	PlaylistID    string `json:"playlist_id,omitempty"`
	PlaylistIndex int    `json:"playlist_index,omitempty"`
	PlaylistCount int    `json:"playlist_count,omitempty"`
	PlaylistTitle string `json:"playlist_title,omitempty"`

	Entries []*VideoInfo `json:"entries,omitempty"`
}

// FormatFilter is a user-provided predicate for filtering formats.
type FormatFilter func(Format) bool

// Phase identifies which stage of processing a Progress event describes.
type Phase string

const (
	PhaseDownload Phase = "download" // fetching a media stream over HTTP
	PhaseMerge    Phase = "merge"    // muxing separate audio/video tracks
	PhaseAudio    Phase = "audio"    // extracting/transcoding audio
	PhaseEmbed    Phase = "embed"    // embedding metadata/thumbnail/subs
)

// Progress reports the advancement of one processing phase for one video.
//
// Cur and Tot are opaque units that depend on Phase (bytes for PhaseDownload,
// milliseconds of media time for the ffmpeg phases). Consumers that only want
// a progress bar should use Fraction and ignore the raw units. Tot is <= 0 when
// the total is not yet known.
//
// During concurrent or multi-format work the same VideoID is reported across
// several events (one per FormatID for downloads, one per phase otherwise);
// aggregate by VideoID if a single per-video number is desired.
type Progress struct {
	VideoID  string
	Title    string
	Phase    Phase
	FormatID string // set for PhaseDownload; empty otherwise
	Cur      int64
	Tot      int64
}

// Fraction returns completion in the range [0,1], or -1 when the total is
// unknown (in which case render an indeterminate indicator rather than a bar).
func (p Progress) Fraction() float64 {
	if p.Tot <= 0 {
		return -1
	}
	f := float64(p.Cur) / float64(p.Tot)
	if f > 1 {
		return 1
	}
	return f
}

// ProgressFunc receives Progress events. The engine serializes invocations, so
// implementations need not be safe for concurrent use.
type ProgressFunc func(Progress)

// DownloadFailure captures structured context about a single failed video.
type DownloadFailure struct {
	VideoID   string `json:"video_id"`
	Title     string `json:"title,omitempty"`
	URL       string `json:"url,omitempty"`
	FormatID  string `json:"format_id,omitempty"`
	Stage     string `json:"stage"` // "extract", "select", "download", "merge", "convert", "embed", "subtitle"
	Error     string `json:"error"`
	Retryable bool   `json:"retryable"`
}

// PlaylistReport summarizes the outcome of a playlist download run.
type PlaylistReport struct {
	Total     int
	Succeeded int
	Failed    []DownloadFailure
	Skipped   int
}

// IsPlaylist returns true if the info represents a playlist.
func (v *VideoInfo) IsPlaylist() bool {
	return len(v.Entries) > 0
}
