// Package ytgo provides public types used throughout ytgo.
package ytgo

import "time"

// Format represents a single downloadable stream.
type Format struct {
	FormatID       string  `json:"format_id"`
	URL            string  `json:"url"`
	ManifestURL    string  `json:"manifest_url,omitempty"`
	Ext            string  `json:"ext"`
	Width          int     `json:"width,omitempty"`
	Height         int     `json:"height,omitempty"`
	FPS            float64 `json:"fps,omitempty"`
	VideoCodec     string  `json:"vcodec,omitempty"`
	AudioCodec     string  `json:"acodec,omitempty"`
	VBR            float64 `json:"vbr,omitempty"`
	ABR            float64 `json:"abr,omitempty"`
	TBR            float64 `json:"tbr,omitempty"`
	Filesize       int64   `json:"filesize,omitempty"`
	FilesizeApprox int64   `json:"filesize_approx,omitempty"`
	Quality        string  `json:"quality,omitempty"`
	QualityLabel   string  `json:"quality_label,omitempty"`
	AudioChannels  int     `json:"audio_channels,omitempty"`
	Language       string  `json:"language,omitempty"`
	HasVideo       bool    `json:"has_video"`
	HasAudio       bool    `json:"has_audio"`
}

// Subtitle represents a subtitle track.
type Subtitle struct {
	URL           string `json:"url"`
	Ext           string `json:"ext"`
	Language      string `json:"language"`
	Name          string `json:"name"`
	AutoGenerated bool   `json:"auto_generated"`
}

// Thumbnail represents a thumbnail image.
type Thumbnail struct {
	URL    string `json:"url"`
	Width  int    `json:"width"`
	Height int    `json:"height"`
	ID     string `json:"id,omitempty"`
}

// Chapter represents a video chapter marker.
type Chapter struct {
	Title     string        `json:"title"`
	StartTime time.Duration `json:"start_time"`
	EndTime   time.Duration `json:"end_time,omitempty"`
}

// VideoInfo holds all metadata for a video or playlist entry.
type VideoInfo struct {
	ID          string        `json:"id"`
	Title       string        `json:"title"`
	Description string        `json:"description,omitempty"`
	Uploader    string        `json:"uploader,omitempty"`
	UploaderID  string        `json:"uploader_id,omitempty"`
	Channel     string        `json:"channel,omitempty"`
	ChannelID   string        `json:"channel_id,omitempty"`
	UploadDate  string        `json:"upload_date,omitempty"`
	Duration    time.Duration `json:"duration,omitempty"`
	ViewCount   int64         `json:"view_count,omitempty"`
	LikeCount   int64         `json:"like_count,omitempty"`
	WebpageURL  string        `json:"webpage_url,omitempty"`
	OriginalURL string        `json:"original_url,omitempty"`

	Formats       []Format              `json:"formats"`
	Thumbnails    []Thumbnail           `json:"thumbnails,omitempty"`
	Subtitles     map[string][]Subtitle `json:"subtitles,omitempty"`
	AutoSubtitles map[string][]Subtitle `json:"automatic_captions,omitempty"`
	Chapters      []Chapter             `json:"chapters,omitempty"`

	Playlist      string `json:"playlist,omitempty"`
	PlaylistID    string `json:"playlist_id,omitempty"`
	PlaylistIndex int    `json:"playlist_index,omitempty"`
	PlaylistCount int    `json:"playlist_count,omitempty"`
	PlaylistTitle string `json:"playlist_title,omitempty"`

	Entries []*VideoInfo `json:"entries,omitempty"`
}

// IsPlaylist returns true if the info represents a playlist.
func (v *VideoInfo) IsPlaylist() bool {
	return len(v.Entries) > 0
}
